[tools]
go = "1.27"
kubectl = "1.37"
mr-boxington = "1.22"
node = "25"
python = "3.14"
rust = { version = "1.99", mr_boxington = true }

[settings]
idiomatic_version_file_enable_tools = ["python"]
python.uv_venv_auto = true
