[tools]
go = "1.27"
kubectl = "latest"
mr-boxington = "latest"
node = "25"
python = "3.14"
rust = { version = "latest", mr_boxington = true }

[settings]
idiomatic_version_file_enable_tools = ["python"]
python.uv_venv_auto = true
