tap "buo/cask-upgrade"
tap "cantino/mcfly", "https://github.com/cantino/mcfly"
tap "charmbracelet/tap"
tap "domt4/autoupdate"
tap "github/gh"
tap "gphotosuploader/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "khanhas/tap"
tap "samuelmeuli/tap"
tap "zaquestion/tap"
brew "openssl@1.1"
brew "autojump"
brew "awscli@1"
brew "bat"
brew "binaryen"
brew "black"
brew "brew-gem"
brew "buildkit"
brew "caddy"
brew "gettext"
brew "pkg-config"
brew "clisp"
brew "cmake"
brew "code-minimap"
brew "freetds"
brew "libsodium"
brew "php"
brew "composer"
brew "coreutils"
brew "corkscrew"
brew "ctags"
brew "deno"
brew "dive"
brew "django-completion"
brew "dnsmasq", restart_service: true
brew "docker", link: false
brew "docker-compose", link: false
brew "docker-compose-completion"
brew "doitlive"
brew "dos2unix"
brew "efm-langserver"
brew "exa"
brew "exercism"
brew "fd"
brew "guile"
brew "gnutls"
brew "sdl2"
brew "snappy"
brew "zeromq"
brew "ffmpeg"
brew "fontforge"
brew "frpc", restart_service: true
brew "fzf"
brew "gawk"
brew "gdb"
brew "go"
brew "gh"
brew "gifsicle"
brew "git-extras"
brew "git-lfs"
brew "gitlab-runner"
brew "graphviz"
brew "haproxy"
brew "helm"
brew "htop"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "node"
brew "insect"
brew "iproute2mac"
brew "jq"
brew "kubernetes-cli"
brew "launchctl-completion"
brew "libmagic"
brew "libsecret"
brew "libxml2"
brew "llvm"
brew "lsd"
brew "luajit", args: ["HEAD"]
brew "magic-wormhole"
brew "mariadb-connector-c"
brew "mas"
brew "maven"
brew "mosh"
brew "mtr"
brew "mycli"
brew "mysql", restart_service: true
brew "mysql-client"
brew "neofetch"
brew "tree-sitter"
brew "neovim"
brew "netcat"
brew "nginx"
brew "numpy"
brew "open-completion"
brew "opencc"
brew "pandoc"
brew "pdm"
brew "pip-completion"
brew "pipx"
brew "plantuml"
brew "podman"
brew "poetry"
brew "pre-commit"
brew "procs"
brew "pstree"
brew "pyenv"
brew "pyenv-virtualenvwrapper"
brew "qcachegrind"
brew "qt"
brew "rbenv"
brew "rbenv-gemset"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "ripgrep"
brew "roswell"
brew "ruby"
brew "rust"
brew "rust-analyzer"
brew "rustc-completion"
brew "shellcheck"
brew "spark"
brew "stern"
brew "stow"
brew "streamlink"
brew "telnet"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "tldr"
brew "tmux"
brew "tree"
brew "watch"
brew "websocat"
brew "wget"
brew "wifi-password"
brew "yarn"
brew "yarn-completion"
brew "youtube-dl"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "cantino/mcfly/mcfly"
brew "samuelmeuli/tap/tmignore"
brew "zaquestion/tap/lab"
cask "aerial"
cask "alacritty"
cask "android-platform-tools"
cask "background-music"
cask "bleunlock"
cask "cakebrew"
cask "docker"
cask "mysql-connector-python"
cask "soundflower"
cask "soundflowerbed"
cask "squirrel"
cask "timemachineeditor"
cask "wireshark"
mas "1Password 7", id: 1333542190
mas "iMazing HEIC Converter", id: 1292198261
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "LastPass", id: 926036361
mas "Medis", id: 1579200037
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft To Do", id: 1274495053
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "QQ", id: 451108668
mas "Tailscale", id: 1475387142
mas "The Unarchiver", id: 425424353
mas "Tweetbot", id: 1384080005
mas "WeChat", id: 836500024
mas "Xcode", id: 497799835
